### ISSUE TITLE
Uncaught ReferenceError: main is not defined

### ISSUE THREAD

**Issue by andys8** [purescript/trypurescript#284]
The seems to be a small issue that a call to `main` is not working. It can be reproduced, but it doesn't seem to affect functionality.

## How to reproduce the issue

* Open https://try.purescript.org
* Open the browser console

> Uncaught ReferenceError: main is not defined

![image](https://user-images.githubusercontent.com/13085980/178460927-10ad1912-65b8-401b-99ac-1eaa74e205df.png)

![image](https://user-images.githubusercontent.com/13085980/178460791-0633c1d3-9d09-4e9d-85a7-3d8a5e4edd51.png)

**Comment by JordanMartinez** [comment]
I can't reproduce this.

**Comment by JordanMartinez** [comment]
So, I thought `main` here referred to the `frame.js`'s `main` that I add to call the compiled module's JS code. However, the `main` referenced here is the client's code.

The issue is caused by this line in [`package.json`](https://github.com/purescript/trypurescript/blob/master/client/package.json#L10)

I was using `spago bundle-app`, which I forgot adds the final `main();` call before bundling it. So, in the `bundle` script, my extra addition of a `main();` call via the `--footer:js=\"\n\nmain();\"` arg passed to `esbuild` is what causes this reference error.
