### ISSUE TITLE
Use icons instead of text in the toolbar

### ISSUE THREAD

**Issue by paf31** [purescript/trypurescript#35]
Now that we have tooltips, we could use icons like the ones from FontAwesome to render the buttons in the toolbar.

**Comment by soupi** [comment]
Why not both?

**Comment by paf31** [comment]
That could work too.

**Comment by hdgarrood** [comment]
I have to say I'm not a big fan of icons instead of text; I find that text is generally much better at explaining what a button is going to do, and I'd prefer not to have to hover over it to get a tooltip to see. I'm also not sure what icon would be appropriate for "auto-compile" or "show JS". Close this?
